package LeetCode.Hard;
/*
Example 1:
Input: s = "ADOBECODEBANC", t = "ABC"
Output: "BANC"
Explanation: The minimum window substring "BANC" includes 'A', 'B', and 'C' from string t.

Example 2:
Input: s = "a", t = "a"
Output: "a"
Explanation: The entire string s is the minimum window.

Example 3:
Input: s = "a", t = "aa"
Output: ""
Explanation: Both 'a's from t must be included in the window.
Since the largest window of s only has one 'a', return empty string.

"aaaaaaaaaaaabbbbbcdd", "abcdd" -> "abbbbbcdd"

s || t
"aaaaaaaaaaaabbbbbcdd" || "abcdd"
"caccaacaaaabbcaccaccc" || "acccacbccc"
"aaaaaaaaaaaabbbbbcdd" || "abcdd"
"cbbbacccccbbbacbabbabacbabbbabaacbaccccbcbcbcca" || "abcbcabaacccababacbabcacbc"
"babb" || "baba"


"e"
"Y"

"g"
"g"

"zxgsxsczeymhaqkerxyumpjazzjfqsgRVJWEHWXNOUOpsorapwtdlyhxoplpvyVCQYSOGYAXNjwnpnrivyftoalcqnkptmudwpic"
"OVUCOQNYXSWOHGEYWAJXVNR"

"zzzzzzzzz"
"zzzzzzzzzz"

"HRULTrctorlsshmgtarxadgosylsmxsorskzqfdkujoJQTUHzRLPPyjllmvqopolorblqrijdpytjzxxvnyqihohrszawlvetnrgcnrknuandawlfzthoeoeiqsxliroreemjvqfzuimacidfymmpyljzxtwatvqszhtsjsmpgzjozxvcygidhsunqtvlbvamafbjmplrbrehjmvvlxyluuaqgbrmfxrygeylkzlflbfcwqnemigwhrrshdqiwvifoifxsaxfyqnibcwrkffbtjqxjubgrfvexqhocdvyyavdmujnfwwecqkantiaogsrgvwtwwkcczydpevynzvirsppgrdmfhbdtczprkrrvxxlxjcvauaharesmqjxhjwmrrtspsbobgofrnvdzbwiibqhrrqbtxyspnszwpxbqrwtavsmhhqrqkjegvhbeftfbicnhamhwyonlwlzysocyzshhyknbdkelplkkvazqpnzhydraoyiodssA"
"HRULTPQPJA"

"RBCPEYZQBMHUMPFLRRUELWUXBLNRTZHLKZMKBEQPNRLTVVYMZJQGVWRHBQCYFMMVCCZXBGDFZJVVYKWXVSNRNIUQNPKCETURLVQBVZMJQOGFTODPPJLFWDWUELJUUvamwdzmthclrlftcjhqadncmirlmzopyzgeamfdjqowanvsfhbdoegawcdnfholkmbvsjtfijgzoimzwspmozwhlkyusyxtstlaoiubxuxcancdKBPCECUOIBTUQBKDYIWUGGGWOFULSXHFBULUDFJPOFOJZBVRTCPQIRSXKVJFGXCVMYQHWGJMVTRPEKZLZRLXWERLPUMQYPBlhcbetrmdjjcslbzcayvtxkpczonehbyvrplbrpjtbwbqwnmhpftcjmdxlmiRCEZBHMFRULUBNTHKMBQNLVYZQVRBCFMCZBDZVYWVNNUNKEULQVMQGTDPLWWEJUUMXZQFDZIYYJRWVGJPMHYZXJDRVJEBKHhffnxramgnukqvcutbqhlgxuhtgoxudeqrcisnmtqcztsyeqdlklbuiwkqzobuitspvohwliaknzzpppexcnaeepejntqdviyhekbwwxdjuaghqjfrksponrdwkdemedsntxuhgvwbjA"
"RBCPEYZQBMHUMPFLRRUELWUXBLNRTZHLKZMKBEQPNRLTVVYMZJQGVWRHBQCYFMMVCCZXBGDFZJVVYKWXVSNRNIUQNPKCETURLVQBVZMJQOGFTODPPJLFWDWUELJUUBUFMHXXZSQLFUDFZOIWYGYGJGRUWWVIGYJDPKMBHQYUZTXBJIDORUVCJEECBPKBHKA"

"ABCllBBBBBlllllllABCDEFAAAllBBBBllZ"
"ABAAACDEFZ"

"ZSLDMKRUWQRDUHYZPEKTCSFOCIBQJVFZRBQVLNDVLHYKELDIHFOWMLDWCZTSTDJFKZOIQOGZYCOMCDBCMMQQURWNQNEKHSMLZMHPXVRCDQOZQKFXQJYXHEIPPLWQOSVTDZIHUNMOVZHBEDUJEFVLLLRNSUMWLWNBFSQXLRKVCQHRCWNFMIRVJQRISDCIJZYTHHOVBQOXPEVWOLTWYINUWWLNCOMZXPJNGNTWYIWQJFKVCTHCJERXLQOBBFHHZRFJJSIQYQDWYBTYKMQVFHOKHUMGPVIPWZGTMCKZEGWGKXIHUIJWJZMOULSMHQWZSPFTRDLZUVNWXBCKYESRNXFSSDIDWGVMQZOZEDSUGJMKUNMGMVWHFFBTWUMNJCKHXVRLSNWOTLGXQHNKSMSDRBIYWDTRGDZJHIGMIZNOKLOZVESGGQBLMBIWCOHSTRQEVZA"
"AhxByySKjQEmNdfgyqVhLuXKELUmNwBKnoxXMeOQOxqphcmftZkiqyzGOEUmtLhrBCbYkWNGrFhTaeWxrdNnwGFDFnVWHtXdJXUFqoEdoCRaqhMeXchQljqMlbJgcnsgVzxdduFVGGlxpzmIWZCLLJHfclwtRKGckNmitLXJaqEPzQaoGkdfUmSWuxsXSsihtOEeXEhIcDKjuyPdDbsVfroicpYNcPtegIMskYRRgXObOXfwPRrajGzxuCxNqgxIlSDGPhEuVlNqVQajUJpOZUMjXxsObrVhcViRidPvizmyOmDCoUnXbocUBweIdMPfmbzbvBEmDooZpYEdrOIJpFxmRdVhIEVSwYaJqWqbflPKSbrPhCgUFvaGViZTdkYYXSgpFbLRrIjsjrStTHdBqFbfsbgSOsSTdCXsRmZLhiuWosgjlcPXUzTLUFtmgNgooqteQqMvxDpJVTQjFvHYrmOqWfFpnHBUkiCaYCQpDZKSoPOnmVDavpxckwusmFsLQESlJulplWoucfcvNSbXNYHPINlSfBZHWGcPxykQurSzjfgLxtKMLyFDjJJuOoqrFrcLmYYuMcqeRKoIBIoOlUyHznxsHwibUTuTaaQopMSJqVxLZRfutStGcIVNhrbFgDHVBTCocxlHvBLlINXHYBuJpdGvZqXenqnJHuQvBpVnLOpMBYEcPOlTWoYUBvTTTvQcvJMglYgshNzxbHuhXfdedJJeSJCqhakDNlNjIREgCXhogTfxBiBbghIyyJjTVJVWQdqCyEpYTMloxLbxtJNXqfwJCvQcezblztCegIHorfHnoeEEBZrwPeveKqRxCyZImzjVRgaRkIkRqzxCjsTgKvkVvlIVIiKUPCybvHcWlhZntixLaHxEYjjdEWzyDNqOHRhheOTacIsCncMfRCLUwlWMGgDskDiaKFVFkvzsBGqrpywgvkjokjyeaxxfintejzyedqsycwtdzqhocktoqloyyeocexoxmpfgiyecollixxasxemwzsxucfdfuysnmmmzwrdvxgpirbzhechkqjxvswskbjtlhserzgnwfnqyyorjgfvlricsjesucykzbgfbaujcigyirgtpatwdhfwoujjoryryywpevwzixeocjigrrkzsgfjudawrzwnrpcsjfuplqbqkprcgrnjbtdepgjkhbgbuuumikevbqwgeukdbystfxhhqbgsgsmpwxauwlvtgrypqwufjveitlxytgmvzwptbhqfixadtvgropzodnkyspchuuknjtmctrmewztoyffliaktdcmolbimndnfelazwwbogyjvdzhvthiegoerlghlubmucxnadosforhzstbrzeplnwnelrxaijphventqqavqksqvvepnjejtqfhjrgbhwxqxwxpvreryyizyqbuzuifgpeexanoculgkxnpupgqndpcqvzlnbsxszafhsorkpvjpfzsjmbuifqxkfdemyqlgcpaodpyhihviekqbywvtubujfjglocsxaccxpwtumxeijtoqafokjrsdwjavnwcvtclqemkoadvkaydupveyijejpblkvicygovadnzexsplomzkfxstghgrhorbnpumxrdyytktekbwewwbmlbxcmhvhpmdqvsioethwawkaoiyxlusoaolpeetatdcqegtyfpsynsnrhbwnjjmsiqazstmwqvilemwzhjzlmubserxwuzqasgvwldkobgsouieebbbrituligojxrklsaiwvvzkpuyjvtymeprfarjdbonzlqepcreldeqnwrhzxtbbmvorrkmxcffpotkzznsatezzagcthclkzobsfcvcvijbzqvdwqlhnqbizkjjrwloswaexufzswbdghjadnuruqjmzjkijdqcwmxwfxzadartconewannbnmzgdzgnuinrabdhfhxwsplwzfnaandtdogzjijqadbvebzywuymgihdzvbxbudqeyalmr"

"GBFVFKDDGMWULCRMCITORHONDWEYEHLZWHCPUKIVIVKTCRIRRVIZCRKPZBEEHHICQCJXNJLMTYECQWVJVTJIBBTXCERINNDCJSJJXHNYMJQTTTBUYWTOPEYBMOLVBQHJXZGJBYHXNILBHCTBVHDFNVIGSRZLVJSMQTTUHHUOIBIKRMYYLFOJJDFLMKLSQPGWHZBSNIPHYNXSNWJSEQLFDVOPSKZDQCYCUBHFWOYHFQTVJDMQNFULTUXPWLZRXCTSOSFBHTSIRLFSXYYTZVGFUCPSKPWJYSVEIVRFJIOEYZDEBPMIBUXUCDOPRVVOXMUZOJUQVNVEPGDSINCGRPXOOXRRYMIPNYVDPKDIEXEOSXWSUGQPEJXLNGKRHJLLCZWIGGVFVJMQXMRCEFUXJXHWVFDFGNWTFGNWYCBLUEOGZOQOMXKBNULEKXLVNEQKSBA"


 */
//
// USE TWO POINTER STRATEGY
//
public class MinimumWindowSubstring {
    public static void main(String[] args) {
        String s ="ADOBECODEBANC";
        MinimumWindowSubstring mws = new MinimumWindowSubstring();
        System.out.println(mws.minWindow(s,"ABC"));
    }

    public String minWindow(String s, String t) {

        return "";
    }
}
